apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Darshit
  title: Test
  description: adas dasd ad asdas
  annotations:
    backstage.io/kubernetes-id: Darshit
    backstage.io/techdocs-ref: dir:.
    jira/project-key: 3123
    jira/component: 123
    jira/label: 123
  links:
    - url: https://example.com/some/page
      title: test
      icon: feedback
      type: asdasdasd
spec:
  type: service
  system: system:default/devhub
  lifecycle: experimental
  owner: group:default/dhc-eng-admin
