apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: darshit-service-github
  title: darshit-service-github
  description: hey this my service updated v2
  annotations:
    backstage.io/kubernetes-id: darshit-service
    servicenow.com/appcode: DEVH-001
    # jira/project-key: DEVHUB
    # old plugin
    # jira/project-key: RHIDP
    # jira/all-issues-jql: project in (RHIDP, RHDHBUGS, RHDHSUPP) and Team in (ec74d716-af36-4b3c-950f-f79213d08f71-4403) and statusCategory != Done ORDER BY updatedDate DESC
    # new plugins
    jira/project-key: RHIDP,RHDHBUGS,RHDHSUPP
    jira/jql: >-
      Team in (ec74d716-af36-4b3c-950f-f79213d08f71-4403)
      and statusCategory != Done
      ORDER BY updatedDate DESC
    backstage.io/techdocs-ref: url:https://github.com/skosina-test/devhub-hello-world-starter/blob/main/
    backstage.io/source-location: url:https://github.com/dhedpara-rh/darshit-gh-service/blob/main/
  links:
    - title: Slack
      url: https://redhat.enterprise.slack.com/archives/C06SX8L9RAQ
      icon: chat
spec:
  type: service
  system: system:default/hello-world
  lifecycle: production
  owner: user:default/dhedpara
