apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: darshit-service
  title: darshit-service
  annotations:
    backstage.io/kubernetes-id: darshit-service
    servicenow.com/appcode: APM0001001
    backstage.io/techdocs-ref: url:https://github.com/CodeNectar/techdocs-example
    backstage.io/techdocs-ref: url:https://github.com/skosina-test/devhub-hello-world-starter
spec:
  type: service
  system: system:default/hello-world
  lifecycle: experimental
  owner: user:default/dhedpara
