apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test
  title: test
  description: adsasdasdas dasd ad asd asd asd asd 
  annotations:
    backstage.io/kubernetes-id: test
    backstage.io/techdocs-ref: dir:.
    jira/project-key: test
    jira/component: test
    jira/label: test
    pagerduty.com/service-id: testsetst
    sonarqube.org/project-key: test
spec:
  type: service
  system: system:default/akamai-cdn
  lifecycle: experimental
  owner: group:default/dhc-eng-admin
